### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by LaraJuliusson** [ucd-cws/arcpy_metadata#60]
Greetings. When I run setup.py in ArcGIS Pro using the command prompt, I get the following error. Any thoughts? 
Thank you,
Lara

Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'arcpy_metadata'

![image](https://github.com/ucd-cws/arcpy_metadata/assets/143522597/b7c0aac5-76af-4f30-86d0-a23c73bfe62e)

**Comment by nickrsan** [comment]
Hi Lara,

The direct cause of your error is that setup.py needs to be run in the Windows command prompt using ArcGIS's Python interpreter, not from within ArcGIS itself (thanks for the screenshot showing that).

But that's unfortunately not going to help in this case because arcpy_metadata only works in ArcMap, not in ArcGIS Pro. Esri *has* now added the functionality we'd need to extend arcpy_metadata to run in ArcGIS Pro (and maybe it'd be good to do so for code portability), but nobody has had time to update this package to run in ArcGIS Pro yet. So even if you changed how you ran the installer, it still won't work.

Still, a big reason we haven't prioritized the update is that ArcGIS Pro has its own ways of accessing and writing metadata from Python. You can find out more about that here: https://pro.arcgis.com/en/pro-app/latest/arcpy/metadata/what-is-the-metadata-module.htm

**Comment by LaraJuliusson** [comment]
Thanks for all the info Nick. I should have realized your tool was for
ArcMap. I was excited to see it because it looks like it includes field
parameters, whereas the ArcGIS Pro python functions don't. They seem to
have a very limited number of metadata elements that you can input/update
via python.

Anyway, thanks again for your help!
Lara
